//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookings()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int room_id { get; set; }
        public System.DateTime check_in_date { get; set; }
        public System.DateTime check_out_date { get; set; }
        public int guests_number { get; set; }
        public decimal total_price { get; set; }
        public Nullable<int> booking_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string special_requests { get; set; }
    
        public virtual Booking_status Booking_status1 { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
