//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_request
    {
        public int request_id { get; set; }
        public Nullable<int> photo_doc { get; set; }
        public string request_text { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Photos Photos { get; set; }
        public virtual Users Users { get; set; }
    }
}
