//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities : DbContext
    {
        public hotelEntities()
            : base("name=hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_status> Booking_status { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Manager_request> Manager_request { get; set; }
        public virtual DbSet<Payment_status> Payment_status { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<RoomTypes> RoomTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<v_Active_Bookings> v_Active_Bookings { get; set; }
        public virtual DbSet<v_Bookings_Details> v_Bookings_Details { get; set; }
        public virtual DbSet<v_Hotel_Reviews> v_Hotel_Reviews { get; set; }
        public virtual DbSet<v_Hotels_with_Photos> v_Hotels_with_Photos { get; set; }
        public virtual DbSet<v_Manager_Requests> v_Manager_Requests { get; set; }
        public virtual DbSet<v_Rooms_Details> v_Rooms_Details { get; set; }
    }
}
