//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public int booking_id { get; set; }
        public decimal amount { get; set; }
        public string payment_method { get; set; }
        public Nullable<int> payment_status { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Payment_status Payment_status1 { get; set; }
    }
}
