//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int review_id { get; set; }
        public int user_id { get; set; }
        public int hotel_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string review_text { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string hotel_response { get; set; }
    
        public virtual Hotels Hotels { get; set; }
        public virtual Users Users { get; set; }
    }
}
