//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rooms()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int room_id { get; set; }
        public int hotel_id { get; set; }
        public int type_id { get; set; }
        public string description { get; set; }
        public int capacity { get; set; }
        public int quantity_available { get; set; }
        public decimal price_per_night { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> room_preview { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Hotels Hotels { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual RoomTypes RoomTypes { get; set; }
    }
}
