//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Bookings_Details
    {
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public string user_fio { get; set; }
        public int room_id { get; set; }
        public string room_description { get; set; }
        public System.DateTime check_in_date { get; set; }
        public System.DateTime check_out_date { get; set; }
        public int guests_number { get; set; }
        public decimal total_price { get; set; }
        public string booking_status { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public string payment_status { get; set; }
    }
}
