//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Manager_Requests
    {
        public int request_id { get; set; }
        public int user_id { get; set; }
        public string user_fio { get; set; }
        public byte[] doc_photo { get; set; }
        public string request_text { get; set; }
    }
}
