//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serverapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Rooms_Details
    {
        public int room_id { get; set; }
        public int hotel_id { get; set; }
        public string room_type_name { get; set; }
        public string description { get; set; }
        public int capacity { get; set; }
        public int quantity_available { get; set; }
        public decimal price_per_night { get; set; }
        public Nullable<int> size { get; set; }
        public byte[] room_photo { get; set; }
    }
}
